definitions:
  steps: &steps
    - step: &base
        name: '(Dev) Webapp'
        runs-on: &base-runs-on
          - 'self.hosted'
          - 'linux'
          - 'ebpearls'
        script: &base-code-deploy-pipe
          - pipe: atlassian/aws-code-deploy:0.2.10
            variables: &base-code-deploy-vars
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              COMMAND: 'upload'

pipelines:
  branches:
    dev:
      - step:
          name: '(Dev) Webapp'
          runs-on: *base-runs-on
          script:
            - apt install zip
            - mv cicd/dev/buildspec.yml .
            - zip -r ycp-dev-webapp.zip .
            - <<: *base-code-deploy-pipe
              variables:
                <<: *base-code-deploy-vars
                APPLICATION_NAME: 'ycp-dev'
                S3_BUCKET: 'ycp-code-src/dev'
                ZIP_FILE: 'ycp-dev-webapp.zip'
                VERSION_LABEL: 'ycp-dev-webapp.zip'
    stage:
      - step:
          name: '(stage) Webapp'
          runs-on: *base-runs-on
          script:
            - apt install zip
            - mv cicd/stage/buildspec.yml .
            - zip -r ycp-stage-webapp.zip .
            - <<: *base-code-deploy-pipe
              variables:
                <<: *base-code-deploy-vars
                APPLICATION_NAME: 'ycp-stage'
                S3_BUCKET: 'ycp-code-src/stage'
                ZIP_FILE: 'ycp-stage-webapp.zip'
                VERSION_LABEL: 'ycp-stage-webapp.zip'

