#!/bin/bash

set -e

aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 721923618792.dkr.ecr.ap-southeast-2.amazonaws.com

cd /home/youchoosepets/project/stage/
docker-compose pull webapp_stage
docker-compose rm -s -f webapp_stage
docker-compose up -d webapp_stage
docker image prune -f

